In [1]:
import numpy as np
blank = np.array([])
blank

array([], dtype=float64)

In [2]:
type(blank)

numpy.ndarray

In [4]:
numlist = [30,709,20,-12,35]
print(numlist, type(numlist))
arr1 = np.array(numlist)
print(arr1, type(arr1))

[30, 709, 20, -12, 35] <class 'list'>
[ 30 709  20 -12  35] <class 'numpy.ndarray'>


In [5]:
len(arr1)

5

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1

array([ 30, 709,  20, -12,  35])

In [8]:
arr1.shape # single dimensional array

(5,)

In [9]:
arr1.ndim #no. of dimensions

1

In [10]:
numlist2 = [[2,3,4],[16,15,28],[45,10,19]]
numlist2

[[2, 3, 4], [16, 15, 28], [45, 10, 19]]

In [11]:
import numpy as np
arr2 = np.array(numlist2)
arr2

array([[ 2,  3,  4],
       [16, 15, 28],
       [45, 10, 19]])

In [12]:
#no. of items
arr2.size

9

In [13]:
new_arr =np.array([[5,18,5,3],[49,17,55,16],[9,19,3,36]])
new_arr

array([[ 5, 18,  5,  3],
       [49, 17, 55, 16],
       [ 9, 19,  3, 36]])

In [14]:
new_arr.shape

(3, 4)

In [15]:
new_arr.ndim

2

In [16]:
new_arr.size

12

In [17]:
#reshape an array
new_arr.reshape(3,2,2)

array([[[ 5, 18],
        [ 5,  3]],

       [[49, 17],
        [55, 16]],

       [[ 9, 19],
        [ 3, 36]]])

In [18]:
new_arr #arrays are not mutable like lists

array([[ 5, 18,  5,  3],
       [49, 17, 55, 16],
       [ 9, 19,  3, 36]])